[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ModeRL"
version = "0.1.0"
description = "Mode remaining exploration for model-based-reinforcement learning in TensorFlow/GPflow."
license = {text = "Apache-2.0"}
keywords = ["model-based reinforcement learning","mixtures-of-gaussian-process-experts", "gaussian-processes", "machine-learning", "variational-inference"]
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    # "gpflow",
    # "numpy",
    # "matplotlib",
    # "scikit-learn",  # for test_train_split
    # 'dataclasses; python_version<"3.6"',
    # "tensor_annotations",
    # "tensor_annotations_tensorflow_stubs",
    "mosvgpe @ git+https://github.com/aidanscannell/mosvgpe#egg=mosvgpe",
    "geoflow @ git+https://github.com/aidanscannell/geoflow#egg=geoflow",
    "wandb",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Mathematics",
]

[project.optional-dependencies]
dev = ["black", "python-language-server[all]", "isort", "pyflakes", "pytest"]
examples = ["pandas", "jupyter", "hydra-core", "simenvs @ git+https://github.com/aidanscannell/simenvs#egg=simenvs"]

[tool.setuptools]
packages = ["moderl"]
