[tool.poetry]
name = "sim-envs"
version = "0.1.0"
description = ""
authors = ["Aidan Scannell <scannell.aidan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "tensorflow"
tensorflow = "^2.3.1"
matplotlib = "^3.3.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.6.4"
pyflakes = "^2.2.0"
# Sphinx = "^3.3.1"
# sphinx-rtd-theme = "^0.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
