defaults:
  - algorithm: pets
  - dynamics_model: two_modes
  - overrides: pets_cartpole
  - action_optimizer: cem
  - env_name: "velocity-controlled-point-mass/scenario-7"
  - initial_dataset:

wandb:
  entity:

seed: 42
log_frequency_agent: 1000
logging_epoch_freq: 100  # plot images every logging_epoch_freq epochs

experiment: default

root_dir: "./experiments"
hydra:
  run:
    dir: ${root_dir}/${overrides.env}/${now:%Y.%m.%d}/${now:%H%M%S}

  sweep:
    dir: ${root_dir}/${overrides.env}/${now:%Y.%m.%d}/${now:%H%M%S}
